language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
script:
  - npm run ci
after_script:
  - bash <(curl -s https://codecov.io/bash)
after_success:
  - npm run semantic-release
